### ISSUE TITLE
implement basic send & receive pages

### ISSUE THREAD

**Issue by ghost** [p9c/pod#100]
just a single ordinary single send with value. we need sanitisers anyway so make the sanitiser for floating point values as well as in this case the maximum spend.

**Comment by l0k18** [comment]
and the receive page don't forget

**Comment by l0k18** [comment]
receive page is now done

**Comment by l0k18** [comment]
starting on send page, basic spec is a simple single send transaction and a simple addressbook with labels for addresses, that is populated by the form (send and save button, save the amount doesn't matter)

**Comment by l0k18** [comment]
Some notes about the implementation:

Neither send nor receive addressbooks can have entries added without message/label annotations. These are just clutter. So unless a receive has both fields filled, it won't store a new entry or update the QR code this way, nor store a send address.

To enforce this, the regenerate button should be inactive if either field contains nothing. The user will grasp intuitively that the QR code is not a new address if they haven't been able to press the regenerate button.

Similarly, the send button will remain inactive until there is both an amount and a label/message. This is simpler than indicating error fields anyway, and the user will not have to guess many times to figure out this is why the button doesn't activate, only one character has to be in both fields and it will light.

Now, there is a security and UX side to this - sometimes scammers may trick someone into sending a payment. By forcing the user to make a note about it, they at least will be able to see by the record (it will show up on tx view when that is implemented also) what this payment was "for", and in the case of being scammed, the note will help the user recognise what has happened, so they can warn others about this incident and provide a meaningful story about it, assisted by their having to make a note what it is.

Further, it is bad accounting practice anyhow to leave a payment without annotation, as good money management requires occasional audits of the records and missing annotations are next to useless, since, while the address is a useful data point, it is not going to remind the user at all what the payment was about, and if no other record can be found bearing the address, the user has to scratch their head about what the payment was for. The lazy user who doesn't care can just put one character in the field, but they have at least been forced to make any note, which might prompt them to question their lazy accounting practices.

**Comment by l0k18** [comment]
Basic functionality is now done, what remains is proper feedback and a password prompt.

**Comment by l0k18** [comment]
have now got send recording txid in the transaction, next can retrieve txid and generate other view mode for card with tx details as per other tx details which are being done in the other issue concurrent with this one at the moment. For that, this requires a bit of a change to design as it needs two distinct buttons for this view where the tx info list detail view can be just one button to show details and only the tx view needs more buttons to copy tx details out

**Comment by l0k18** [comment]
this is pretty much done now
